In [1]:
import pandas as pd
import matplotlib 
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## Data Load

In [2]:

analysisYear = '2020'

dfMOB = pd.read_csv(f'data/{analysisYear}_US_Region_Mobility_Report.csv',parse_dates=['date'])

dfPOL = pd.read_csv(f'data/USA_policy_{analysisYear}.csv',parse_dates=['Date'])

In [3]:
dfPOL.head()

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,92232,United States,USA,NaN,NaN,NAT_TOTAL,2020-01-01,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,92233,United States,USA,NaN,NaN,NAT_TOTAL,2020-01-02,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,92234,United States,USA,NaN,NaN,NAT_TOTAL,2020-01-03,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,92235,United States,USA,NaN,NaN,NAT_TOTAL,2020-01-04,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,92236,United States,USA,NaN,NaN,NAT_TOTAL,2020-01-05,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
dfMOB.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

## Preprocessing : Mobility

Creates `dfMOB`, `dfMOB_state`, `dfMOB_county`

In [5]:
dfMOB.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [6]:
dfMOB = dfMOB.rename(columns={'retail_and_recreation_percent_change_from_baseline':'retail',
                  'grocery_and_pharmacy_percent_change_from_baseline':'grocery_pharmacy',
                  'transit_stations_percent_change_from_baseline':'transit',
                  'workplaces_percent_change_from_baseline':'workplaces',
                  'residential_percent_change_from_baseline':'residential',
                 'parks_percent_change_from_baseline':'residential'
                  })

In [7]:
dfMOB = dfMOB.dropna(subset=['sub_region_1'])

In [8]:
dfMOB

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail,grocery_pharmacy,residential,transit,workplaces,residential
321,US,United States,Alabama,NaN,NaN,US-AL,NaN,ChIJdf5LHzR_hogR6czIUzU0VV4,2020-02-15,5.0,2.0,39.0,7.0,2.0,-1.0
322,US,United States,Alabama,NaN,NaN,US-AL,NaN,ChIJdf5LHzR_hogR6czIUzU0VV4,2020-02-16,0.0,-2.0,-7.0,3.0,-1.0,1.0
323,US,United States,Alabama,NaN,NaN,US-AL,NaN,ChIJdf5LHzR_hogR6czIUzU0VV4,2020-02-17,3.0,0.0,17.0,7.0,-17.0,4.0
324,US,United States,Alabama,NaN,NaN,US-AL,NaN,ChIJdf5LHzR_hogR6czIUzU0VV4,2020-02-18,-4.0,-3.0,-11.0,-1.0,1.0,2.0
325,US,United States,Alabama,NaN,NaN,US-AL,NaN,ChIJdf5LHzR_hogR6czIUzU0VV4,2020-02-19,4.0,1.0,6.0,4.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812060,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN
812061,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-28,NaN,NaN,NaN,NaN,-40.0,NaN
812062,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-29,NaN,NaN,NaN,NaN,-43.0,NaN
812063,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-30,NaN,NaN,NaN,NaN,-40.0,NaN
812064,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-31,NaN,NaN,NaN,NaN,-38.0,NaN

In [9]:
ogColumns = dfMOB.columns.tolist()

for removeName in ['country_region_code',
               'country_region',
               'metro_area',
               'sub_region_1',
              'census_fips_code',
              'place_id',]:
    ogColumns.remove(removeName)
    
dfMOB = dfMOB[ogColumns]
dfMOB_state = dfMOB.dropna(subset=['iso_3166_2_code'])
dfMOB_county = dfMOB.dropna(subset=['sub_region_2'])
dfMOB_state['iso_3166_2_code'] = dfMOB_state['iso_3166_2_code']\
                                .apply(lambda x: x.split('-')[1])

## Preprocessing : Policy 

creates `NATPOLCHANGE` and `STATEPOLCHANGE`

### National Policy

In [10]:
# National 
dfPOL[dfPOL['Jurisdiction']=='NAT_TOTAL']
# State Policies
dfPOL[dfPOL['Jurisdiction']=='STATE_TOTAL']

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
366,92598,United States,USA,Alaska,US_AK,STATE_TOTAL,2020-01-01,0.0,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
367,92599,United States,USA,Alaska,US_AK,STATE_TOTAL,2020-01-02,0.0,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
368,92600,United States,USA,Alaska,US_AK,STATE_TOTAL,2020-01-03,0.0,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
369,92601,United States,USA,Alaska,US_AK,STATE_TOTAL,2020-01-04,0.0,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
370,92602,United States,USA,Alaska,US_AK,STATE_TOTAL,2020-01-05,0.0,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19027,111259,United States,USA,Wyoming,US_WY,STATE_TOTAL,2020-12-27,2.0,0.0,NaN,...,68.52,68.52,72.62,72.62,63.75,63.75,65.71,65.71,50.0,50.0
19028,111260,United States,USA,Wyoming,US_WY,STATE_TOTAL,2020-12-28,2.0,0.0,NaN,...,68.52,68.52,72.62,72.62,63.75,63.75,65.71,65.71,50.0,50.0
19029,111261,United States,USA,Wyoming,US_WY,STATE_TOTAL,2020-12-29,2.0,0.0,NaN,...,68.52,68.52,72.62,72.62,63.75,63.75,65.71,65.71,50.0,50.0
19030,111262,United States,USA,Wyoming,US_WY,STATE_TOTAL,2020-12-30,1.0,1.0,Jackson schools are hybrid and will continue t...,...,61.11,61.11,72.62,72.62,60.83,60.83,62.38,62.38,50.0,50.0
19031,111263,United States,USA,Wyoming,US_WY,STATE_TOTAL,2020-12-31,1.0,1.0,NaN,...,61.11,61.11,72.62,72.62,60.83,60.83,62.38,62.38,50.0,50.0

In [11]:
# Policy Data 
dfPOLnat = dfPOL[dfPOL['Jurisdiction']=='NAT_TOTAL']

In [12]:
polColumns = [
    'C1_School closing',
    'C6_Stay at home requirements',
    'C2_Workplace closing',
    'C7_Restrictions on internal movement',
    'C3_Cancel public events',
    'C4_Restrictions on gatherings',
    'C5_Close public transport',
    'H2_Testing policy'
]

In [13]:
# National Policies
dfPOLnat = dfPOLnat[polColumns+['Date']]

In [14]:
dfPOLnat = dfPOLnat.sort_values(by=['Date'])

In [15]:
for policyName  in polColumns:
    dfPOLnat['diff_'+policyName] = dfPOLnat.loc[:,policyName]\
    .rolling(window=2)\
    .apply(lambda x: x.iloc[1] - x.iloc[0])

In [16]:
dfPOLnat

,C1_School closing,C6_Stay at home requirements,C2_Workplace closing,C7_Restrictions on internal movement,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,H2_Testing policy,Date,diff_C1_School closing,diff_C6_Stay at home requirements,diff_C2_Workplace closing,diff_C7_Restrictions on internal movement,diff_C3_Cancel public events,diff_C4_Restrictions on gatherings,diff_C5_Close public transport,diff_H2_Testing policy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,3.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2020-12-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,3.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2020-12-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
363,3.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2020-12-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
364,3.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2020-12-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
365,3.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2020-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
DATELIST = []

for policyName  in polColumns:
    diffColumn = 'diff_'+policyName
    
    dates_of_change = dfPOLnat.dropna()[dfPOLnat[diffColumn]!=0]['Date'].to_list()
    values_of_change = dfPOLnat.dropna()[dfPOLnat[diffColumn]!=0][diffColumn].to_list()
    
    for index in range(len(dates_of_change)):
        DATELIST.append({
            'policy_name' : policyName,
            'dates_of_change':dates_of_change[index],
            'value' : values_of_change[index],
            'jur' : 'NAT'
        })

In [18]:
NATPOLCHANGE = pd.DataFrame(DATELIST)

In [19]:
NATPOLCHANGE

                             policy_name dates_of_change  value  jur
0                      C1_School closing      2020-03-05    3.0  NAT
1           C6_Stay at home requirements      2020-03-15    2.0  NAT
2           C6_Stay at home requirements      2020-07-20   -1.0  NAT
3           C6_Stay at home requirements      2020-10-13    1.0  NAT
4           C6_Stay at home requirements      2020-10-26   -1.0  NAT
5           C6_Stay at home requirements      2020-11-16    1.0  NAT
6                   C2_Workplace closing      2020-03-19    3.0  NAT
7                   C2_Workplace closing      2020-06-15   -1.0  NAT
8                   C2_Workplace closing      2020-11-16    1.0  NAT
9                   C2_Workplace closing      2020-12-02   -1.0  NAT
10  C7_Restrictions on internal movement      2020-03-14    1.0  NAT
11  C7_Restrictions on internal movement      2020-03-19    1.0  NAT
12               C3_Cancel public events      2020-03-01    1.0  NAT
13               C3_Cancel public events      2020-03-12    1.0  NAT
14         C4_Restrictions on gatherings      2020-03-11    1.0  NAT
15         C4_Restrictions on gatherings      2020-03-12    1.0  NAT
16         C4_Restrictions on gatherings      2020-03-21    2.0  NAT
17         C4_Restrictions on gatherings      2020-09-12   -1.0  NAT
18         C4_Restrictions on gatherings      2020-11-16    1.0  NAT
19             C5_Close public transport      2020-03-17    1.0  NAT
20                     H2_Testing policy      2020-02-28    1.0  NAT
21                     H2_Testing policy      2020-03-04    1.0  NAT
22                     H2_Testing policy      2020-03-14    1.0  NAT

### State Policy

In [20]:
# Policy Data 
dfPOLstate = dfPOL[dfPOL['Jurisdiction']=='STATE_TOTAL']

In [21]:
dfPOLstate['RegionCode'] = dfPOLstate['RegionCode'].apply(lambda x: x.split('_')[1])

In [22]:
STATEOP = []

In [23]:

for stateName in dfPOLstate['RegionCode'].unique():
    stateDF = dfPOLstate[dfPOLstate['RegionCode']==stateName]
    polColumns = [
    'C1_School closing',
    'C6_Stay at home requirements',
    'C2_Workplace closing',
    'C7_Restrictions on internal movement',
    'C3_Cancel public events',
    'C4_Restrictions on gatherings',
    'C5_Close public transport',
    'H2_Testing policy'
    ]
    
    stateDF = stateDF[polColumns+['Date']]
    stateDF = stateDF.sort_values(by=['Date'])
    for policyName  in polColumns:
        stateDF['diff_'+policyName] = stateDF.loc[:,policyName]\
        .rolling(window=2)\
        .apply(lambda x: x.iloc[1] - x.iloc[0])
        
    DATELIST = []

    for policyName  in polColumns:
        diffColumn = 'diff_'+policyName

        dates_of_change = stateDF.dropna()[stateDF[diffColumn]!=0]['Date'].to_list()
        values_of_change = stateDF.dropna()[stateDF[diffColumn]!=0][diffColumn].to_list()

        for index in range(len(dates_of_change)):
            DATELIST.append({
                'policy_name' : policyName,
                'dates_of_change':dates_of_change[index],
                'value' : values_of_change[index],
                'jur' : stateName
            })
            
    STATEOP.append(pd.DataFrame(DATELIST))

In [24]:
STATEPOLCHANGE = pd.concat(STATEOP)

In [25]:
STATEPOLCHANGE

                     policy_name dates_of_change  value jur
0              C1_School closing      2020-03-13    1.0  AK
1              C1_School closing      2020-03-16    2.0  AK
2   C6_Stay at home requirements      2020-03-22    2.0  AK
3   C6_Stay at home requirements      2020-04-24   -1.0  AK
4           C2_Workplace closing      2020-03-12    1.0  AK
..                           ...             ...    ...  ..
23             H2_Testing policy      2020-01-21    1.0  WY
24             H2_Testing policy      2020-03-02   -1.0  WY
25             H2_Testing policy      2020-03-04    1.0  WY
26             H2_Testing policy      2020-04-22    1.0  WY
27             H2_Testing policy      2020-10-14    1.0  WY

[1359 rows x 4 columns]

## Preprocessing : Cases